version: "3.8"

services:
  # nginx:
  #   container_name: nginx
  #   image: 42-nginx:stable
  #   build:
  #     context: ./services/nginx
  #   ports:
  #     - 443:443
  #   networks:
  #     - default
  #   restart: always
  #   depends_on:
  #     - wordpress
  #     - mariadb
  #
  wordpress:
    container_name: wordpress
    image: 42-wordpress:stable
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - static-content:/var/www/html
    networks:
      - default
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: 42-mariadb:stable
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - db-data:/data/db
    networks:
      - default

networks:
  default:
    driver: bridge

# TODO: Update the volumes to bind to /home/bcorrea/data
volumes:
  db-data:
  static-content:
