version: "3.8"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - 443:443
    volumes:
      - static-content:/var/www/html
    networks:
      - default
    depends_on:
      - wordpress
      - mariadb

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - static-content:/var/www/html
    networks:
      - default
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  db-data:
    driver_opts:
      type: none
      device: /home/bcorrea/data/mysql
      o: bind
  static-content:
    driver_opts:
      type: none
      device: /home/bcorrea/data/html
      o: bind
